import Head from 'next/head'
import MainLayout from '@/components/layouts/mainlayout'

export default function Home() {
	return (
		<>
			<Head>
				<title>Tour Journey</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<MainLayout>
				<h1>lsdkjfasldkfjdsklafj</h1>
			</MainLayout>
		</>
	)
}
